### retrieve things

GET {{host}}/api/v1/things
Content-Type: application/json
Accept: application/json


### switch ON

POST {{host}}/api/v1/switch/c9e4c231-dbca-428f-9442-b01440f91330/8a1ea8db-fffa-4c6f-935e-39a34eba871c
Content-Type: application/json
Accept: application/json

{
  "switch": "ON"
}

### add thing

POST {{host}}/api/v1/things/add/c9e4c231-dbca-428f-9442-b01440f91330
Content-Type: application/json
Accept: application/json

{
  "name": "new name",
  "type": "LAMP"
}

### remove thing

POST {{host}}/api/v1/things/remove/c9e4c231-dbca-428f-9442-b01440f91330/19851c6d-89ad-48c9-9b0c-9abb9eb92eea
Content-Type: application/json
Accept: application/json
